### ISSUE TITLE
Configure prod

### ISSUE THREAD

**Issue by dosumis** [obophenotype/bds-pipeline-config#3]
Leave this:

```yaml
allow_entities_without_labels: true
index: false
testmode: false
batch: true
safe_label: loose
batch_size: 100000000
relation_type_threshold: 0.95
represent_values_and_annotations_as_json:
  iris:
    - "http://purl.obolibrary.org/obo/IAO_0000115"
    - "http://www.geneontology.org/formats/oboInOwl#hasExactSynonym"
    - "http://www.geneontology.org/formats/oboInOwl#hasNarrowSynonym"
    - "http://www.geneontology.org/formats/oboInOwl#hasBroadSynonym"
    - "http://www.geneontology.org/formats/oboInOwl#hasRelatedSynonym"
```

Remove this and everything under it:

```yaml
property_mapping:
```

Shawn to edit to remove existing content and add upper level groupings for cell types:
```
neo_node_labelling:
```

Shawn to edit to replace curie_map with one from BDS ontology repo.
``` yaml
curie_map:
```
