### ISSUE TITLE
Apply neo:labels for cell types to taxonomy nodes.

### ISSUE THREAD

**Issue by dosumis** [obophenotype/bds-pipeline-config#7]
```yaml
neo_node_labelling:
  - classes:
      - CL:0011005
    label: GABAergic
```

->

```yaml
neo_node_labelling:
  - classes:
      - CL:0011005
      - BDSHELP:exemplar_of some CL:0011005
    label: GABAergic
```

For all cell type nodes

Depends on @hkir-dev completing [addition of relation and extension of robot templates ](https://github.com/obophenotype/brain_data_standards_ontologies/issues/76#issuecomment-814966197)
